image: docker

variables:
  IMAGE_TAG: "${CI_PROJECT_ID}-${CI_COMMIT_SHA}"

stages:
  - build

job1:
  stage: build
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
